#header intvec.inc()
*
         org  $ffd6
         fdb  isci
         fdb  ispi
         fdb  ipai
         fdb  ipao
         fdb  itimo
         fdb  iti4o5
         fdb  itoc4
         fdb  itoc3
         fdb  itoc2
         fdb  itoc1
         fdb  itic3
         fdb  itic2
         fdb  itic1
         fdb  irti
         fdb  irq
         fdb  inmi
         fdb  isw
         fdb  iopc
         fdb  icopf
         fdb  icmf
         fdb  reset
*
